<?php

namespace AppBundle\Repository;

/**
 * character_traitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class character_traitsRepository extends \Doctrine\ORM\EntityRepository
{
}
