<?php

namespace AppBundle\Repository;

/**
 * character_profileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class character_profileRepository extends \Doctrine\ORM\EntityRepository
{
}
