<?php

namespace AppBundle\Repository;

/**
 * clanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clanRepository extends \Doctrine\ORM\EntityRepository
{
}
