<?php

namespace AppBundle\Repository;

/**
 * clan_disciplinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clan_disciplinesRepository extends \Doctrine\ORM\EntityRepository
{
}
