<?php

namespace AppBundle\Repository;

/**
 * combat_recordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class combat_recordRepository extends \Doctrine\ORM\EntityRepository
{
}
