<?php

namespace AppBundle\Repository;

/**
 * point_schemasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class point_schemasRepository extends \Doctrine\ORM\EntityRepository
{
}
