<?php

namespace AppBundle\Repository;

/**
 * trait_levelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trait_levelRepository extends \Doctrine\ORM\EntityRepository
{
}
