<?php

namespace AppBundle\Repository;

/**
 * trait_entityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trait_entityRepository extends \Doctrine\ORM\EntityRepository
{
}
