<?php

namespace AppBundle\Repository;

/**
 * trait_sub_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trait_sub_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
