<?php

namespace AppBundle\Repository;

/**
 * typesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typesRepository extends \Doctrine\ORM\EntityRepository
{
}
